---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[met-server::default]
      - recipe[ulimit2::default]
      - recipe[met-kvalobs::default]
      - recipe[met-kvalobs::kvusers]
      - recipe[met-kvalobs::corba]
      - recipe[met-kvalobs::postgres]
      - recipe[met-kvalobs::kvalobs-database]
      - recipe[met-kvalobs::kvalobs]
      - recipe[met-kvalobs::postgres]
    attributes:
    attributes:
  - name: database
    run_list:
      - recipe[met-kvalobs::postgres]
    attributes:
    attributes: {
      "met-kvalobs": {
        "corba": {
          "endPointPublish": ""
        },
        "met-server": {
          "apt": {
            "devel":  true
          }
        }
      }
    }
  
