---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[met-kvalobs::default]
      - recipe[met-kvalobs::corba]
      - recipe[met-kvalobs::postgres]
      - recipe[met-kvalobs::kvalobs-database]
      - recipe[met-kvalobs::kvalobs]
    attributes:
  
