name                'met-kvalobs'
maintainer          'kvalobs-dev, MET Norway'
maintainer_email    'kvalobs-dev@met.no'
license             'GNU GPL 2.0'
description         'Installs/Configures kvalobs'
long_description    'Installs/Configures kvalobs'
version             '0.1.0'

depends             'met-server', '~> 0.57.3'
depends             'ulimit2',    '~> 0.2.0'
depends             'sysctl',     '~> 0.6.2'
depends             'postgresql', '~> 3.4.20'
